#!/usr/bin/env python3
"""Generate public and TypeScript rubric artifacts from the Python registry."""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
RUBRIC_PATH = (
    REPOSITORY_ROOT
    / "services"
    / "sermon-evaluator"
    / "src"
    / "sermon_evaluator"
    / "rubric.py"
)
RUBRIC_SPEC = importlib.util.spec_from_file_location(
    "sermon_evaluator_rubric_registry", RUBRIC_PATH
)
if RUBRIC_SPEC is None or RUBRIC_SPEC.loader is None:
    raise RuntimeError(f"Could not load rubric registry from {RUBRIC_PATH}")
RUBRIC_MODULE = importlib.util.module_from_spec(RUBRIC_SPEC)
sys.modules[RUBRIC_SPEC.name] = RUBRIC_MODULE
RUBRIC_SPEC.loader.exec_module(RUBRIC_MODULE)

AGGREGATES = RUBRIC_MODULE.AGGREGATES
CRITERIA_COUNT = RUBRIC_MODULE.CRITERIA_COUNT
RUBRIC_SECTIONS = RUBRIC_MODULE.RUBRIC_SECTIONS
RUBRIC_VERSION = RUBRIC_MODULE.RUBRIC_VERSION
render_framework_aggregates = RUBRIC_MODULE.render_framework_aggregates
render_framework_rubric = RUBRIC_MODULE.render_framework_rubric


FRAMEWORK_PATH = (
    REPOSITORY_ROOT / "content" / "pages" / "sermon-evaluation" / "framework.md"
)
TYPESCRIPT_PATH = (
    REPOSITORY_ROOT / "lib" / "sermon-evaluation" / "rubric.generated.ts"
)


def replace_generated_block(
    source: str, name: str, generated: str
) -> str:
    start = f"<!-- BEGIN GENERATED: {name} -->"
    end = f"<!-- END GENERATED: {name} -->"
    if source.count(start) != 1 or source.count(end) != 1:
        raise ValueError(f"Expected exactly one generated block named {name}")
    before, remainder = source.split(start, 1)
    _, after = remainder.split(end, 1)
    return f"{before}{start}\n{generated.rstrip()}\n{end}{after}"


def render_framework(current: str) -> str:
    current = replace_generated_block(
        current, "RUBRIC", render_framework_rubric()
    )
    return replace_generated_block(
        current, "AGGREGATES", render_framework_aggregates()
    )


def render_typescript() -> str:
    sections = [
        {
            "key": section.key,
            "label": section.label,
            "gateOnly": section.gate_only,
            "criteria": [
                {"key": criterion.key, "label": criterion.label}
                for criterion in section.criteria
            ],
        }
        for section in RUBRIC_SECTIONS
    ]
    aggregates = [
        {
            "key": aggregate.key,
            "clientKey": aggregate.client_key,
            "label": aggregate.label,
            "weight": aggregate.weight,
            "members": list(aggregate.members),
        }
        for aggregate in AGGREGATES
    ]
    return (
        "// Generated by scripts/generate-sermon-framework.py. Do not edit.\n"
        f"export const SERMON_RUBRIC_VERSION = {json.dumps(RUBRIC_VERSION)} as const;\n"
        f"export const SERMON_CRITERIA_COUNT = {CRITERIA_COUNT} as const;\n"
        "export const SERMON_RUBRIC_SECTIONS = "
        f"{json.dumps(sections, indent=2)} as const;\n"
        "export const SERMON_AGGREGATES = "
        f"{json.dumps(aggregates, indent=2)} as const;\n"
    )


def update_or_check(path: Path, expected: str, *, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == expected:
        return True
    if check:
        print(f"Generated artifact is stale: {path.relative_to(REPOSITORY_ROOT)}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"Updated {path.relative_to(REPOSITORY_ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    current_framework = FRAMEWORK_PATH.read_text(encoding="utf-8")
    expected_framework = render_framework(current_framework)
    results = [
        update_or_check(
            FRAMEWORK_PATH, expected_framework, check=args.check
        ),
        update_or_check(
            TYPESCRIPT_PATH, render_typescript(), check=args.check
        ),
    ]
    return 0 if all(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
